name: node
type: nodejs:10

dependencies:
  nodejs:
    pm2: "^2.0.0"

relationships:
  chrome: "chrome:chrome-headless"

web:
  commands:
    start: "PM2_HOME=$PLATFORM_APP_DIR/run pm2 start index.js --no-daemon"
    #in this setup you will find your application stdout and stderr in /app/run/logs
  locations:
    "/public":
      passthru: false
      root: "public"
      # Whether to allow files not matching a rule or not.
      allow: true
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
          allow: true
        ^/robots\.txt$:
          allow: true

mounts:
    "/run": "shared:files/run"
    'screenshots':
        source: local
        source_path: screenshots
    'pdfs':
        source: local
        source_path: pdfs

disk: 512
